
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 16
#define YY_END_OF_BUFFER 17
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[276] =
    {   0,
        0,    0,   17,   14,    4,   13,    3,   14,   14,    9,
        9,    8,    8,    5,    8,   14,    7,    8,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   12,    4,    0,
        0,    9,    9,    8,    8,    5,    8,    0,    7,    8,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        3,    0,    0,    0,    9,    9,    0,    0,   10,    8,
        8,    5,    0,    0,    7,    0,    0,    0,    0,    0,
       11,    0,    0,    0,    0,    0,    0,    0,    0,    6,
        0,    0,    0,   11,    0,    0,    2,    2,    0,    0,
        0,    0,    0,    1,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,   11,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    7,    0,
        0,    0,    0,    0,    0,   15,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   11,    0,
        0,    0,   15,    0,    0,    0,   15,    0,    0,    0,
        0,   15,    0,    0,    0,    0,    0,    0,    0,    0,
        1,    0,    0,    0,    0,   15,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   15,    0,    0,    0,    0,
       15,    0,    0,    0,    0,    0,   11,    0,    0,    0,
        0,    0,    0,   15,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   10,    0,    0,
        0,   15,    0,    0,    0,    0,   15,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   15,    0,    0,
        0,    0,    0,    0,   15,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   10,    0,    0,    0,    0,    0,
        0,   10,    0,    0,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    1,    1,    6,    7,
        8,    9,   10,   11,   12,    1,   13,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   14,    1,
       15,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   16,    1,    1,    1,    1,   17,   18,   19,    1,

       20,   21,    1,   22,   23,    1,    1,   24,   25,   26,
       27,   28,    1,   29,   30,   31,   32,   33,   34,    1,
       35,    1,   36,    1,   37,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[38] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    3,    1,    1,
        1,    1,    1,    4,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[308] =
    {   0,
        0,    0,  670, 1187,   36,   50,   58,    0,  652,   59,
       69,   72,   73,   76,   77,   81,   82,   89,   82,  638,
      629,   76,   69,   69,  625,  616,  618, 1187,    0,  105,
      629,  108,  112,  115,  116,  119,  120,  612,  125,  132,
      116,  602,  598,  116,  112,  112,  594,  594,  587,  147,
      150,  600,  597,  139,  151,  159,  164,   56, 1187,  154,
      167,  171,  584,  586,  172,  575,   11,  570,  549,  534,
      176,  529,  534,  533,  520,  519,  503,  514,  513,  177,
      156,  490,  490, 1187,  495,  487,  503, 1187,  497,  493,
      486,  175,  491, 1187,  489,  468,  458,  443,  452,  184,

      190,  438,  437,  427,  427, 1187,  429,  424,  420,  414,
      397,  399,  410,  188,  405,  200,  196,  403, 1187,  372,
      362,  201,  211,  217,  221, 1187,  226,  373,  355,  358,
      344,  335,  340,  332,  320,  199,  326,  201, 1187,  232,
      236,  249,  328,  253,  263,  269,  319,  281,  274,  284,
      310,  297,  280,  262,  262,  245,  251,  239,  244,  236,
      225,  295,  314,  324,  336,  242,  348,  216,  331,  377,
      343,  300,  362,  381,  393,  397,  367,  407,  419,  412,
      218,  431,  197,  191,  173,  162, 1187,  461,  495,  424,
      436,  446,  509,  461,  521,  471,  475,  479,  550,  564,

      578,  441,  156,  499,  133,  593,  251,  130,  627,  526,
      641,  536,  554,  568,  593,  605,  120,  516,  608,  655,
      540,  253,  275,  631,  645,  669,  485,  659,  681,  686,
      710,  559,  586,  705,  288,  722,  724,  676,  736,  751,
      741,  763,  301,  314,  792,  806,  758,  777,  796,  820,
      832,  827,  861,  875,  889,  615,  701,  903,  355,  918,
      693,  849,  852,  749,  108,  953,  362,   82,  988, 1023,
      757,  394,  777,  407, 1187, 1059, 1063, 1067, 1071, 1075,
     1079, 1083, 1087, 1091, 1095, 1099, 1103, 1107, 1111, 1115,
     1119, 1123, 1127, 1131, 1135, 1139, 1142, 1146, 1150, 1154,

     1158, 1162, 1166, 1170, 1174, 1178, 1182
    } ;

static yyconst flex_int16_t yy_def[308] =
    {   0,
      275,    1,  275,  275,  275,  275,    5,  276,  277,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,    5,  275,
        5,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
        5,  276,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  278,  279,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  276,  275,  280,  281,
      278,  278,  279,  275,  282,  275,  275,  275,  275,  283,

      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  280,  280,  281,  275,  284,  282,  275,  275,
      275,  283,  285,  286,  287,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  288,  278,  284,  275,  285,
      285,  289,  290,  283,  285,  286,  275,  283,  287,  291,
      292,  293,  275,  275,  275,  275,  275,  275,  280,  288,
      278,  285,  285,  285,  289,  290,  285,  290,  286,  289,
      286,  287,  291,  291,  294,  295,  287,  291,  292,  287,
      293,  287,  293,  296,  275,  275,  275,  280,  289,  291,
      291,  291,  294,  295,  291,  295,  297,  298,  292,  294,

      292,  299,  296,  300,  275,  280,  280,  280,  294,  297,
      301,  298,  298,  302,  297,  303,  296,  300,  302,  304,
      300,  288,  305,  297,  297,  301,  299,  298,  297,  302,
      306,  229,  229,  303,  296,  299,  302,  300,  302,  304,
      300,  300,  305,  305,  301,  301,  303,  302,  302,  306,
      302,  303,  304,  306,  304,  307,  281,  306,  305,  280,
      307,  281,  275,  281,  281,  305,  305,  281,  305,  280,
      305,  305,  307,  305,    0,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,

      275,  275,  275,  275,  275,  275,  275
    } ;

static yyconst flex_uint16_t yy_nxt[1225] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,    4,    4,    4,   19,   20,
       21,    4,   22,    4,    4,    4,    4,   23,    4,   24,
       25,   26,    4,   27,    4,    4,   28,   29,   30,   31,
       96,   97,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   30,   30,   30,   41,   42,   43,   50,   44,   31,
       55,   51,   55,   45,   89,   46,   47,   48,   90,   49,
       56,   57,   56,   60,   60,   60,   60,   62,   60,   62,
       60,   58,   32,   65,  116,   65,   61,   61,   32,   63,
       60,   61,   60,   64,   66,   61,   71,   73,   67,   75,

       74,   72,   76,   61,   59,   68,   30,   30,   30,   55,
      116,   55,   50,   56,   57,   56,   80,   60,   80,   60,
       62,   60,   62,   60,   58,   32,   65,  204,   65,   61,
       61,   32,   81,   60,   61,   60,   84,   66,  114,   68,
       73,   72,   75,   74,   88,   85,   61,   59,   57,   57,
       57,   31,   55,   51,   55,   60,   53,   60,  139,   58,
       56,   57,   56,  204,   53,   57,   57,   57,   60,   53,
       60,   58,   62,   65,   62,   65,   58,  100,   80,  100,
       80,  187,   59,  117,   66,  109,   97,   94,  123,  124,
      125,  127,  127,  127,   59,  205,  136,  126,  204,   59,

      116,   57,   57,   57,  138,  123,  124,  160,   91,  138,
      184,  113,   58,  161,  126,  141,  142,  122,  122,  122,
      140,  145,  146,  202,  143,  150,  151,  127,  127,  127,
      147,  184,  148,   92,  152,   59,  162,  142,  122,  122,
      162,  142,  122,  122,  160,  143,  140,  140,  188,  143,
      153,  140,  114,  164,  165,  144,  144,  123,  169,  222,
       84,  160,  166,  223,  167,  188,  126,  141,  170,  122,
      122,  122,   71,  145,  171,  139,  143,  188,  150,  151,
      187,  172,  147,  244,  148,  123,  169,  152,  174,  175,
      149,  172,  186,  218,  126,  204,  185,  176,  144,  162,

      142,  122,  122,  188,  150,  151,  144,  172,  143,  244,
      184,  144,  149,  152,  178,  179,  188,  180,  162,  170,
      122,  122,  256,  181,  122,  182,  257,  143,  162,  170,
      122,  122,  140,  122,   92,  145,  146,  143,  140,   84,
      164,  189,  144,  144,  147,  122,  148,  145,  171,  166,
      158,  167,  162,  170,  122,  122,  147,  188,  148,   71,
      139,  143,  157,  244,  188,  163,  190,  175,  149,  172,
      244,  150,  199,  163,  172,  176,  156,  155,  163,  140,
      152,  164,  165,  144,  144,  190,  175,  149,  172,  154,
      166,  139,  167,  106,  176,  173,  188,  192,  193,  177,

      180,  197,  244,  183,  183,  119,  194,  116,  195,  188,
      198,  174,  200,  149,  172,  244,  150,  199,  114,  172,
      176,  149,  135,  178,  201,  152,  180,  134,  190,  175,
      149,  172,  181,   84,  182,  150,  199,  176,  172,   84,
      190,  200,  149,  172,  152,  215,  216,  133,  177,  176,
      190,  200,  149,  172,  217,  132,  177,  131,  130,  176,
      129,  177,  206,  206,  206,  197,  197,  183,  183,  114,
      128,   71,  121,  207,  198,  197,  120,  183,  183,  210,
      211,  202,  202,  214,  198,  203,  204,   71,  212,  215,
      247,  119,  168,   94,   92,  116,  208,  140,  217,  164,

      189,  144,  144,  219,  220,  114,  221,   87,  166,  112,
      167,  173,  126,  192,  209,  177,  180,  111,   84,  110,
      219,  220,  194,  221,  195,  190,  200,  149,  172,  126,
      210,  211,  202,  202,  176,  108,  107,  106,  191,  212,
      214,  105,  203,  204,  219,  220,  191,  221,  104,  168,
      103,  191,  149,  126,  178,  179,  102,  180,  214,  101,
      203,  204,   71,  181,  211,  182,  173,  168,  192,  193,
      177,  180,  230,  231,  218,  221,  197,  194,   99,  195,
      149,  143,  178,  201,  197,  180,   98,   95,   94,  197,
      232,  181,   92,  182,  206,  206,  206,  232,  211,  202,

      202,  114,   88,  197,   87,  207,  212,  202,   86,  233,
      234,  197,  237,  231,  218,  221,  197,  260,  235,   78,
      236,  143,   77,  261,   83,   82,   61,  243,  208,  173,
       31,  192,  209,  177,  180,  210,  245,  202,  202,   79,
      194,   78,  195,  197,  212,  225,  226,  227,  227,  210,
      245,  202,  202,   77,  228,   70,  229,  218,  212,  239,
      240,   69,  241,  214,  214,  203,  204,   54,  147,  275,
      242,  197,  168,  225,  246,  227,  227,  275,  275,  275,
      219,  253,  228,  221,  229,  210,  245,  202,  202,  126,
      230,  231,  218,  221,  212,  260,  275,  275,  224,  143,

      275,  261,  262,  263,  262,  266,  224,  202,  275,  233,
      252,  224,  214,  264,  249,  250,  238,  241,  235,  275,
      236,  275,  275,  166,  275,  251,  215,  247,  230,  231,
      218,  221,  275,  275,  275,  217,  265,  143,  275,  227,
      237,  254,  218,  221,  275,  219,  253,  227,  221,  143,
      275,  116,  227,  218,  126,  239,  255,  267,  241,  188,
      202,  268,  233,  234,  147,  273,  242,  219,  253,  274,
      221,  235,  275,  236,  275,  275,  126,  275,  275,  260,
      238,  230,  254,  218,  221,  261,  275,  275,  238,  266,
      143,  275,  275,  238,  197,  275,  225,  226,  227,  227,

      230,  254,  218,  221,  275,  228,  275,  229,  197,  143,
      225,  246,  227,  227,  275,  275,  275,  275,  275,  228,
      275,  229,  214,  275,  249,  258,  238,  241,  275,  202,
      275,  233,  252,  166,  275,  251,  230,  254,  218,  221,
      235,  275,  236,  275,  275,  143,  275,  275,  275,  248,
      262,  263,  262,   57,   57,   57,  275,  248,  275,  275,
      275,  264,  248,  218,   58,  239,  240,  275,  241,  275,
      275,  275,  275,  275,  147,  275,  242,  214,  275,  249,
      250,  238,  241,  275,  265,  275,  275,   59,  166,  275,
      251,  218,  275,  239,  255,  275,  241,  275,  275,  275,

      275,  275,  147,  275,  242,  214,  275,  249,  258,  238,
      241,  275,  275,  275,  275,  275,  166,  275,  251,  206,
      206,  206,  275,  275,  275,  275,  114,  275,  275,  275,
      207,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  208,  269,  270,  269,  275,  275,  275,
      275,  244,  275,  275,  275,  271,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  272,  269,
      270,  269,  275,  275,  275,  275,  244,  275,  275,  275,

      271,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  272,  206,  206,  206,  275,  275,  275,
      275,  114,  275,  275,  275,  207,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  208,   52,
       52,  275,   52,   53,  275,   53,   53,   91,   91,   91,
       91,   93,   93,   93,   93,  113,  113,  113,  113,  115,
      115,  115,  115,  118,  118,  118,  118,  122,  122,  122,
      122,  137,  137,  137,  137,  140,  140,  140,  140,  144,

      144,  144,  144,  149,  149,  149,  149,  159,  159,  159,
      159,  163,  163,  163,  163,  168,  168,  275,  168,  173,
      173,  173,  173,  177,  177,  177,  177,  183,  183,  183,
      183,  191,  191,  191,  191,  196,  196,  196,  196,  203,
      203,  203,  197,  197,  197,  197,  213,  213,  213,  213,
      202,  202,  202,  202,  218,  218,  218,  218,  224,  224,
      224,  224,  214,  214,  214,  214,  227,  227,  227,  227,
      238,  238,  238,  238,  243,  243,  243,  243,  248,  248,
      248,  248,  259,  259,  259,  259,    3,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,

      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275
    } ;

static yyconst flex_int16_t yy_chk[1225] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    5,
       67,   67,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    6,    6,    6,    5,    5,    5,    6,    5,    7,
       10,    7,   10,    5,   58,    5,    5,    5,   58,    5,
       11,   11,   11,   12,   13,   12,   13,   14,   15,   14,
       15,   11,   13,   17,  268,   17,   12,   13,   15,   16,
       18,   15,   18,   16,   17,   16,   22,   23,   19,   24,

       23,   22,   24,   18,   11,   19,   30,   30,   30,   32,
      265,   32,   30,   33,   33,   33,   34,   35,   34,   35,
       36,   37,   36,   37,   33,   35,   39,  217,   39,   34,
       35,   37,   41,   40,   37,   40,   44,   39,  208,   41,
       45,   44,   46,   45,   54,   46,   40,   33,   50,   50,
       50,   51,   55,   51,   55,   60,   54,   60,  205,   50,
       56,   56,   56,  203,   54,   57,   57,   57,   61,   54,
       61,   56,   62,   65,   62,   65,   57,   71,   80,   71,
       80,  186,   50,   92,   65,   81,   81,   92,  100,  100,
      100,  101,  101,  101,   56,  185,  114,  100,  184,   57,

      114,  116,  116,  116,  117,  122,  122,  136,  117,  138,
      183,  136,  116,  138,  122,  123,  123,  123,  123,  124,
      168,  124,  124,  181,  123,  125,  125,  127,  127,  127,
      124,  181,  124,  161,  125,  116,  140,  140,  140,  140,
      141,  141,  141,  141,  160,  140,  166,  166,  160,  141,
      127,  142,  159,  142,  142,  142,  142,  144,  144,  207,
      158,  222,  142,  207,  142,  222,  144,  145,  145,  145,
      145,  146,  157,  146,  146,  156,  145,  223,  149,  149,
      155,  149,  146,  223,  146,  148,  148,  149,  150,  150,
      150,  150,  154,  235,  148,  235,  153,  150,  148,  162,

      162,  162,  162,  243,  172,  172,  148,  172,  162,  243,
      152,  148,  151,  172,  151,  151,  244,  151,  163,  163,
      163,  163,  244,  151,  147,  151,  244,  163,  164,  164,
      164,  164,  143,  169,  137,  169,  169,  164,  165,  135,
      165,  165,  165,  165,  169,  171,  169,  171,  171,  165,
      134,  165,  167,  167,  167,  167,  171,  259,  171,  133,
      132,  167,  131,  259,  267,  167,  173,  173,  173,  173,
      267,  177,  177,  167,  177,  173,  130,  129,  167,  170,
      177,  170,  170,  170,  170,  174,  174,  174,  174,  128,
      170,  121,  170,  120,  174,  175,  272,  175,  175,  175,

      175,  176,  272,  176,  176,  118,  175,  115,  175,  274,
      176,  178,  178,  178,  178,  274,  180,  180,  113,  180,
      178,  179,  112,  179,  179,  180,  179,  111,  190,  190,
      190,  190,  179,  110,  179,  182,  182,  190,  182,  109,
      191,  191,  191,  191,  182,  202,  202,  108,  182,  191,
      192,  192,  192,  192,  202,  107,  182,  105,  104,  192,
      103,  182,  188,  188,  188,  194,  194,  194,  194,  188,
      102,   99,   98,  188,  194,  196,   97,  196,  196,  197,
      197,  197,  197,  198,  196,  198,  198,   96,  197,  227,
      227,   95,  198,   93,   91,   90,  188,  189,  227,  189,

      189,  189,  189,  204,  204,   89,  204,   87,  189,   86,
      189,  193,  204,  193,  193,  193,  193,   85,   83,   82,
      218,  218,  193,  218,  193,  195,  195,  195,  195,  218,
      210,  210,  210,  210,  195,   79,   78,   77,  195,  210,
      212,   76,  212,  212,  221,  221,  195,  221,   75,  212,
       74,  195,  199,  221,  199,  199,   73,  199,  213,   72,
      213,  213,   70,  199,  232,  199,  200,  213,  200,  200,
      200,  200,  214,  214,  214,  214,  232,  200,   69,  200,
      201,  214,  201,  201,  232,  201,   68,   66,   64,  232,
      233,  201,   63,  201,  206,  206,  206,  215,  215,  215,

      215,  206,   53,  233,   52,  206,  215,  216,   49,  216,
      216,  233,  219,  219,  219,  219,  233,  256,  216,   48,
      216,  219,   47,  256,   43,   42,   38,  256,  206,  209,
       31,  209,  209,  209,  209,  224,  224,  224,  224,   27,
      209,   26,  209,  211,  224,  211,  211,  211,  211,  225,
      225,  225,  225,   25,  211,   21,  211,  220,  225,  220,
      220,   20,  220,  228,  228,  228,  228,    9,  220,    3,
      220,  226,  228,  226,  226,  226,  226,    0,    0,    0,
      238,  238,  226,  238,  226,  229,  229,  229,  229,  238,
      230,  230,  230,  230,  229,  261,    0,    0,  229,  230,

        0,  261,  257,  257,  257,  261,  229,  234,    0,  234,
      234,  229,  231,  257,  231,  231,  231,  231,  234,    0,
      234,    0,    0,  231,    0,  231,  236,  236,  237,  237,
      237,  237,    0,    0,    0,  236,  257,  237,    0,  236,
      239,  239,  239,  239,    0,  241,  241,  236,  241,  239,
        0,  264,  236,  240,  241,  240,  240,  264,  240,  271,
      247,  264,  247,  247,  240,  271,  240,  242,  242,  271,
      242,  247,    0,  247,    0,    0,  242,    0,    0,  273,
      242,  248,  248,  248,  248,  273,    0,    0,  242,  273,
      248,    0,    0,  242,  245,    0,  245,  245,  245,  245,

      249,  249,  249,  249,    0,  245,    0,  245,  246,  249,
      246,  246,  246,  246,    0,    0,    0,    0,    0,  246,
        0,  246,  250,    0,  250,  250,  250,  250,    0,  252,
        0,  252,  252,  250,    0,  250,  251,  251,  251,  251,
      252,    0,  252,    0,    0,  251,    0,    0,    0,  251,
      262,  262,  262,  263,  263,  263,    0,  251,    0,    0,
        0,  262,  251,  253,  263,  253,  253,    0,  253,    0,
        0,    0,    0,    0,  253,    0,  253,  254,    0,  254,
      254,  254,  254,    0,  262,    0,    0,  263,  254,    0,
      254,  255,    0,  255,  255,    0,  255,    0,    0,    0,

        0,    0,  255,    0,  255,  258,    0,  258,  258,  258,
      258,    0,    0,    0,    0,    0,  258,    0,  258,  260,
      260,  260,    0,    0,    0,    0,  260,    0,    0,    0,
      260,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  260,  266,  266,  266,    0,    0,    0,
        0,  266,    0,    0,    0,  266,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  266,  269,
      269,  269,    0,    0,    0,    0,  269,    0,    0,    0,

      269,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  269,  270,  270,  270,    0,    0,    0,
        0,  270,    0,    0,    0,  270,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  270,  276,
      276,    0,  276,  277,    0,  277,  277,  278,  278,  278,
      278,  279,  279,  279,  279,  280,  280,  280,  280,  281,
      281,  281,  281,  282,  282,  282,  282,  283,  283,  283,
      283,  284,  284,  284,  284,  285,  285,  285,  285,  286,

      286,  286,  286,  287,  287,  287,  287,  288,  288,  288,
      288,  289,  289,  289,  289,  290,  290,    0,  290,  291,
      291,  291,  291,  292,  292,  292,  292,  293,  293,  293,
      293,  294,  294,  294,  294,  295,  295,  295,  295,  296,
      296,  296,  297,  297,  297,  297,  298,  298,  298,  298,
      299,  299,  299,  299,  300,  300,  300,  300,  301,  301,
      301,  301,  302,  302,  302,  302,  303,  303,  303,  303,
      304,  304,  304,  304,  305,  305,  305,  305,  306,  306,
      306,  306,  307,  307,  307,  307,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,

      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "indentador.lex"
/*----- Secci�n de Declaraciones --------------*/
#line 4 "indentador.lex"
#include <stdio.h>
#include <stdlib.h>     /* atoi */
#include <ctype.h>      /* tolower */
#include <sys/wait.h>
typedef enum { false, true } bool;

// Variables
long int numIndex   = 0;      // Tabulaciones necesarias
int  esBloque       = 0;      // (Bloque)

bool inicioLinea    = true;
bool insertadaLinea = false;
bool lineaProcesada = false;
bool anteriorLlave  = false;  // Llave '}' solamente
bool salidaFichero  = false;  // Solo se modifica 0/1 veces



// Funciones

// Escribe yytext en pantalla teniendo en cuenta el formato,
// si es inicio de línea imprime las tabulaciones necesarias.
void escribir(){
  int i = 0, j;

  if (inicioLinea){
    while (yytext[i] == ' ' || yytext[i] == '\t')
      ++i;

    for(j=0; j<numIndex; ++j){
      if (salidaFichero)
        fwrite("\t", yyleng, 1, yyout);
      else
        printf("\t");
    }
  }

  if (salidaFichero)
    fwrite(yytext+i, yyleng-i, 1, yyout);
  else
    printf("%s", yytext+i);

  inicioLinea = false;
}


// Esta función es necesaria ya que no debemos cambiar yytext a lo largo
// del programa, además pueden darse situaciones en las que se necesite.
void escribirCadena(char *cadena, int n){
    if (salidaFichero)
      fwrite(cadena, n, 1, yyout);
    else{
      for (int i=0; i<n; ++i)
        printf("%c", cadena[i]);
    }
}


// Nos ayuda a saber si un carácter está dentro de unos paréntesis o no.
void bloque(){
  for (int i=0; i<yyleng; ++i){
    if (yytext[i] == '(')
      ++esBloque;
    else if (yytext[i] == ')')
      --esBloque;
  }
}

// Función claramente indicativa, nos ayuda a ajustar bloques sin saltos
// de línea como:
//    if (condicion) ahorrarespacio();

int ultimoParentesisDerecho(){
  int posParentesis = 0, i;
  for (i=0; i<yyleng; ++i){
    if (yytext[i] == ')')
      posParentesis = i;
  }

  return posParentesis;
}

// Nos dice si tiene comentario yytext, útil para arreglar las estructuras del tipo
// if (condicion) // comentario
// {
//    sentencias;
// }
bool hayComentario(int *lineaComent){
  char antes = ' ', actual;
  bool comentario = false;
  int i;

  for (i=0; i<yyleng && !comentario; ++i){
    actual = yytext[i];
    if ((antes == actual == '/') || ((antes == '/') && (actual == '*'))){
      comentario = true;
      *lineaComent = i-1;
    }
    antes = actual;
  }

  return comentario;
}

// Función para saber en qué expresión regular entra cada vez el programa.
bool boolDepurar = false;
void depurar(char * cadena){
  if (boolDepurar)
    printf("\n------ %s -------\n", cadena); fflush (stdout);
}

/* EXPRESIONES REGULARES */
/* Texto */
/* Estructuras de control */
/* Comentarios */
/* Separaciones con espacios */
#line 949 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 157 "indentador.lex"


  /*----- Sección de Reglas ----------------*/

#line 1172 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 276 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1187 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 161 "indentador.lex"
{depurar("Comentario");
                        escribir(); // Debemos dejarlos igual
                        if (yytext[1] == '*') // Si es un comentario largo
                          escribirCadena("\n", 1);

                        // Consecuencias
                        inicioLinea    = true;
                        insertadaLinea = true;
                        lineaProcesada = false;
                        anteriorLlave  = false;
                       }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 173 "indentador.lex"
{depurar("Cadena texto");
                        escribir(); // Debemos dejarla igual

                        // Consecuencias
                        insertadaLinea = false;
                        anteriorLlave  = false;
                       }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 181 "indentador.lex"
{depurar("Espacios");
                        if (!inicioLinea){
                          escribirCadena(" ", 1); // Conseguimos homogeneidad

                          // Consecuencias
                          insertadaLinea = false;
                          anteriorLlave  = false;
                          inicioLinea = false;
                        }
                       }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 192 "indentador.lex"
{depurar("Tabuladores");
                        if (!inicioLinea){
                          escribirCadena("\t", 1); // Conseguimos homogeneidad

                          // Consecuencias
                          insertadaLinea = false;
                          anteriorLlave  = false;
                          inicioLinea = false;
                        }
                       }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 203 "indentador.lex"
{depurar("Coma");
                        escribirCadena(", ", 2);

                        // Consecuencias
                        insertadaLinea = false;
                        anteriorLlave = false;
                       }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 211 "indentador.lex"
{depurar("Asterisco");
                       escribirCadena(" *", 2);

                       // Consecuencias
                       insertadaLinea = false;
                       anteriorLlave = false;
                      }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 220 "indentador.lex"
{depurar("PuntoComa"); // Separamos esto del espacioVacia por los comentarios
                        int posicion;
                        bool comentario = hayComentario(&posicion);

                        escribirCadena(";", 1);
                        if (comentario){
                          escribirCadena("\t", 1);
                          escribirCadena(yytext+posicion, yyleng-posicion);
                        }

                        if (!esBloque){
                            escribirCadena("\n", 1);
                            inicioLinea    = true;
                            insertadaLinea = true;
                            lineaProcesada = false;
                            anteriorLlave  = false;
                        }
                        else{
                          escribirCadena(" ", 1);
                          anteriorLlave = false;
                        }
                       }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 243 "indentador.lex"
{depurar("Espacio doble");
                        char *c;
                        int i;

                        escribirCadena(" ", 1);
                        for (i=0; i<yyleng; ++i){
                          if (yytext[i] != ' ' && yytext[i] != '\t'){
                          //printf("\n-%c-\n", yytext[i]);fflush(stdout);

                            escribirCadena(yytext+i, 1);

                          }
                        }
                        escribirCadena(" ", 1);

                        // Consecuencias
                        anteriorLlave = false;
                       }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 262 "indentador.lex"
{depurar("Espacio vacío");
                        int antes = esBloque, despues, i;

                        bloque();     // Comprueba si hay nuevos paréntesis
                        despues = esBloque;
                        if ( ((despues - antes) == 1) && (despues == 1) ) // Si es el primer (
                          escribirCadena(" ", 1);

                        for (int i=0; i<yyleng; ++i){
                          if (yytext[i] != ' ' && yytext[i] != '\t')
                            escribirCadena(yytext+i, 1);
                        }

                       }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 277 "indentador.lex"
{depurar("Llave fea");
                        int lineaComent, i;
                        char *c;

                        escribirCadena("){", 2);
                        --esBloque;

                        if (hayComentario(&lineaComent)){
                          for (i=lineaComent; i<(yyleng-1); ++i){
                            *c = yytext[i];
                            escribirCadena(yytext+i, 1);
                          }
                        }

                        if (!lineaProcesada)
                          ++numIndex;

                        escribirCadena("\n", 1);

                        // Consecuencias
                        inicioLinea    = true;
                        insertadaLinea = true;
                        lineaProcesada = false;
                        anteriorLlave  = false; // Usamos este bool solo para llaves '}'
                       }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 303 "indentador.lex"
{depurar("Tipo más"); // Añadimos una tabulación
                        escribir();
                        ++numIndex;

                        // Consecuencias
                        insertadaLinea = false;
                        inicioLinea    = false;
                        lineaProcesada = true;
                        anteriorLlave  = false;
                       }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 315 "indentador.lex"
{depurar("Tipo menos"); // Quitamos una tabulación
                        --numIndex;
                        if (anteriorLlave == false && (!insertadaLinea)){
                          escribirCadena("\n", 1);
                          //printf("--");
                          }
                        escribir();
                        escribirCadena("\n", 1);

                        // Consecuencias
                        insertadaLinea = true;
                        inicioLinea    = true;
                        lineaProcesada = false;
                        anteriorLlave  = true;
                       }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 331 "indentador.lex"
{depurar("Nueva línea");
                        if (!insertadaLinea){
                          escribirCadena("\n", 1);

                          // Consecuencias
                          lineaProcesada = false;
                          inicioLinea    = true;
                          insertadaLinea = true;
                          // Si pones anteriorLlave=false la variable no serviría de nada
                        }
                       }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 343 "indentador.lex"
{depurar("Punto");
                       escribir();

                       // Consecuencias
                       insertadaLinea = false;
                       anteriorLlave  = false;
                      }
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 350 "indentador.lex"
{depurar("Control sin línea"); // Ejemplo: if (condicion) noIntro();
                        int parentesis = ultimoParentesisDerecho(), i=0,j=0, inicio=0;
                        char fila1[yyleng], fila2[yyleng]; // Estructura de control

                        if (parentesis == 0){ // sentencia else
                          int index = 0;
                          while (yytext[index] == ' ' || yytext[index] == '\t')
                            ++index;
                          parentesis = index+4; // else
                        }

                        while (yytext[i] == ' ' || yytext[i] == '\t')
                          ++i;
                        inicio = i;

                        for (i; i<=parentesis; ++i)
                          fila1[i-inicio] = yytext[i];
                        //fila1[i] = '\0';

                        for (int j=0; j<numIndex; ++j)  // Escribimos primera fila
                          escribirCadena("\t", 1);
                        escribirCadena(fila1, parentesis+1-inicio);
                        escribirCadena("{\n", 2);

                        while (yytext[i] == ' ' || yytext[i] == '\t') // Quitamos espacios
                          ++i;
                        i = i-1; // Primera letra de la segunda fila

                        // Escribimos segunda fila
                        for (int k=0; k<(numIndex+1); ++k)
                          escribirCadena("\t", 1);

                        for (int k=0; k<(yyleng-i); ++k)
                          escribirCadena(yytext+i+k, 1);
                        escribirCadena("\n}\n", 3);

                        inicioLinea    = true;
                        insertadaLinea = true;
                        lineaProcesada = false;
                        anteriorLlave  = false;
                       }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 391 "indentador.lex"
ECHO;
	YY_BREAK
#line 1516 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 276 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 276 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 275);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 391 "indentador.lex"



  /*----- Sección de Procedimientos --------*/

int main (int argc, char *argv[]){
  if (argc == 2 || argc == 3){
    yyin = fopen (argv[1], "rt");

    if (yyin == NULL){
      printf ("El fichero %s no se puede abrir para lectura.\n", argv[1]);
      exit (-1);
    }
    if (argc == 3){
       //fichSalida = argv[2];
       //fp = fopen(fichSalida, "w");
       yyout = fopen(argv[2], "w");

       salidaFichero = true;
    }
  }
  else return 1;

  yylex ();
  return 0;
}


